version: '3'
services:
    jdownloader:
        image: jlesage/jdownloader-2
        ports:
            - 5800:5800
            - 3128:3128
        volumes:
            - ./.docker/org.jdownloader.api.RemoteAPIConfig.json:/config/cfg/org.jdownloader.api.RemoteAPIConfig.json

    pytest:
        build:
            context: ./
            dockerfile: pytest.dockerfile
        volumes:
            - .:/pyjd
        depends_on:
            - jdownloader
