name: Run tests

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Start JDownloader
        run: docker compose up -d jdownloader
      - name: Run tests
        run: docker compose up --exit-code-from pytest pytest
